name: community_material_icon
description: A community material design icon flutter packages based on https://materialdesignicons.com/
version: 5.9.55
homepage: https://github.com/ripsware/community_material_icon

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: MaterialDesignIconFont
      fonts:
        - asset: packages/community_material_icon/fonts/materialdesignicons-webfont.ttf
